# Use the official RabbitMQ image with management plugin
FROM rabbitmq:3-management

# Set environment variables for RabbitMQ
ENV RABBITMQ_DEFAULT_USER=admin
ENV RABBITMQ_DEFAULT_PASS=admin

# Expose necessary ports
EXPOSE 15671 15672 25672 5671 5672 4369
